version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672
  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
  metric:
    build:
      context: ./metric
    volumes:
      - "./logs/:/app/logs"
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
  plot:
    build:
      context: ./plot
    volumes:
      - ./logs/:/app/logs
    restart: always
    depends_on:
      - metric